DELETE http://localhost:3001/api/persons/66f7fc09514ffc77911efdfa

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Kpfcdi",
  "number": "048-31-7"
}
###
GET  http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/1
