DELETE http://localhost:3001/api/persons/66f7c63e04a0692a7e3bee12
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "wrfsrtdi",
  "number": "118d9-7014"
}
###
GET  http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/66f802b13f81b4c3756
###
GET http://localhost:3001/info
###
PUT http://localhost:3001/api/persons/66f7c63e04a0692a7e3bee12
